set(LLVM_TRIPLE armv7-unknown-linux-gnueabihf)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_C_FLAGS "-target ${LLVM_TRIPLE} -fuse-ld=lld")
set(CMAKE_CXX_FLAGS "-target ${LLVM_TRIPLE} -fuse-ld=lld")
set(CMAKE_STRIP llvm-strip)
